---
name: PyPI upload

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: actions/checkout@v3
      - run: |
        sed -i 's/0.1.0/'"${CI_COMMIT_REF_NAME}"'/' pyproject.toml
        head -n 6 xml_data_model/__version__.py
      - run: python -m pip install poetry==1.2.2
      - run: poetry build
      - run: |
        poetry config http-basic.pypi ${{ secrets.PYPI_LOGIN }} ${{ secrets.PYPI_PASS }}
        poetry publish
