---
name: PyPI upload

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: dependencies
        run: |
          python -m pip install poetry==1.1.7
      -
        name: build
        run: poetry build
      -
        name: publish
        run: |
          poetry config http-basic.pypi ${{ secrets.PYPI_LOGIN }} ${{ secrets.PYPI_PASS }}
          poetry publish
